### ISSUE TITLE
Wayland issues

### ISSUE THREAD

**Issue by kumitterer** [nqrduck/nqrduck#11]
Some things seem to be a little shaky when using Wayland on Linux. May also be related to #4

**Comment by jupfi** [comment]
Currently this is especially problematic because the locking of the UI doesn't work in wayland. The animations are opened in the background and not played. This makes the UI appear very unresponsive ...

**Comment by jupfi** [comment]
Fixed with v0.0.10 - additional problems  (dialogs not showing up)  have to be fixed in the respective modules.
