### ISSUE TITLE
Automatic documentation

### ISSUE THREAD

**Issue by kumitterer** [nqrduck/nqrduck#30]
Look into things like ReadTheDucks

**Comment by jupfi** [comment]
https://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html

**Comment by jupfi** [comment]
By creating a documentation repo and then adding the different nqrduck modules as git submodules documentation generators like Sphinx can be easily used. 

As sphinx theme PyData could be used.

**Comment by jupfi** [comment]
This is now part of the [NQRduckumentation](github.com/nqrduck/nqrduckumentation)
